### ISSUE TITLE
TypeError: EthereumDater is not a constructor: line 10

### ISSUE THREAD

**Issue by HansBhatia** [kai-thompson/eth-date-to-block#2]
<img width="628" alt="Screen Shot 2023-02-06 at 10 26 14 AM" src="https://user-images.githubusercontent.com/78050086/217012543-7ff10c6d-2d81-4937-90f3-32023cc63ae4.png">
I'm trying to experiment with the library but I was not able to get it to work. Any help would be appreciated!

**Comment by kai-thompson** [comment]
Hey hey! Thanks for reaching out!

Here's a  temporary solution:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/90171376/217017784-9fb3f87b-5781-4bc6-82b3-b91bb723404a.png">

This issue isn't present when using Typescript so that is another option.

I'll get a JS fix out tonight after work. Feel free to ping me if you have any other concerns!
